### ISSUE TITLE
Bug when importing BA from python environment und windows

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#1033]
Error when trying to import bornagain from another python 3.8 interpretor on windows. Can easily be fixed with one line in bornagain/__init__.py

### Steps to reproduce the behavior
Install python3.8 and bornagain on windows.
Run:
```
import sys
sys.path.append(r'C:\BornAgain-1.17.0\python')
import bornagain as ba
```

Raises error as os.add_dll_directory can't handle "."

### Fix:
Replace line 6 in python/bornagain/__init__.py:
```
-                os.add_dll_directory(p)
+                os.add_dll_directory(os.path.abspath(p))
```

### Platforms affected
Windows 10

**Comment by jwuttke** [comment]
Resolved in PR1035.
