### ISSUE TITLE
Crash when importing from python

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#1034]
Trying to import any model from python script crashes the GUI

### Expected behavior
Model will be analyzed and build in GUI or Error raised.

### Actual behavior
GUI crashes instantly without any message.

### Steps to reproduce the behavior
Build any model, simpelest example is:
```
def get_sample():
    # Defining Materials
    material_1 = ba.HomogeneousMaterial("Default", 0.001, 1e-05)

    # Defining Layers
    layer_1 = ba.Layer(material_1)

    # Defining Multilayers
    multiLayer_1 = ba.MultiLayer()
    multiLayer_1.addLayer(layer_1)
    return multiLayer_1
```
Try importing the file in BA.

### Platforms affected
Windows 10 Build 18363, BA 1.17.0

**Comment by jwuttke** [comment]
1.18 release candidate also crashes under Linux.

Short message: "Exception thrown while executing a Python code."

Long message:
```Can't call function



============================================================
PATH: /usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:.:/home/jwu/exe:/home/jwu/exe/var:/home/jwu/exe/photo:/G/int/rbib:/G/int/tps:/usr/local/root/bin
PYTHONPATH: /usr/local/lib/BornAgain-1.17::/G/sw/ba/build/lib:/G/sw/nsxtool/build/swig
PYTHONHOME: 
Py_GetProgramName(): python3
Py_GetProgramFullPath(): /usr/bin/python3
Py_GetPath(): /usr/local/lib/BornAgain-1.17::/G/sw/ba/build/lib:/G/sw/nsxtool/build/swig:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload
Py_GetPythonHome(): 
sys.path: /usr/local/lib/BornAgain-1.17,/io,/G/sw/ba/build/lib,/G/sw/nsxtool/build/swig,/usr/lib/python38.zip,/usr/lib/python3.8,/usr/lib/python3.8/lib-dynload,/usr/local/lib/python3.8/dist-packages,/usr/lib/python3/dist-packages,/usr/local/lib/BornAgain-1.17,/usr/local/lib/BornAgain-1.17/bornagain,
```

**Comment by jwuttke** [comment]
* No error message when importing an empty .py file.
  * Meaningful error message when importing a meaningless .py file: "Python code doesn't contain any function"

**Comment by jwuttke** [comment]
Error message on loading Artur's example comes from PyImportAssistant::createMultiLayer.

**Comment by jwuttke** [comment]
Split into two issues: #1081 on silent crashes; #1082 on error messages from PyImport
