### ISSUE TITLE
Crash on saving to deleted project

### ISSUE THREAD

**Issue by juanmcloaiza** [scgmlz/BornAgain#1060]
## Steps to reproduce:

1. Save a project to some directory
2. Delete the project directory (i.e. the directory created in step 1.)
3. Modify the project inside bornagain
4. Save (`ctrl+s` or click `File > Save Project`)
5. Bornagain opens a pop-up dialog informing about an error (unable to copy-paste)
6. After some seconds, everything freezes and Bornagain crashes abruptly

## Actual behavior:

Bornagain crashes abruptly

## Expected behavior: 

Tell users that the project directory does not exist anymore and allow them to save to a new location, as if `File > Save as...` had been clicked.

## Platforms affected:

Windows 10; Bornagain 1.16, 1.17, 1.17.99

**Comment by mpuchner** [comment]
Investigating this:
* Only happens, if "Autosave=ON"
* More platforms affected: 1.18.0 on Windows, MAC

**Comment by mpuchner** [comment]
Resolved in PR 1135
