### ISSUE TITLE
Verify absolute scale of scattered intensity

### ISSUE THREAD

**Issue by jwuttke** [scgmlz/BornAgain#1090]
to ensure compatibility of scattering with R, T.

Let's do it empirically (as opposed to relying on code analysis): Simulate a simple system in BA, integrate scattered intensity, and compare with paper-and-pencil computation.

**Comment by aglavic** [comment]
Another idea to further verify:
Make a set of simulations over the same detector area with varying pixel sizes and make sure the individual intensities scale with pixel area.

**Comment by jwuttke** [comment]
[IntensityScale.pdf](https://github.com/scgmlz/BornAgain/files/5489904/IntensityScale.pdf)

A thorough investigation, described in the attached report, confirms that both scattering and specular contributions to the 2D detector image are correctly computed in absolute units, and therefore can be compared with each other without any adjustment.
