### ISSUE TITLE
InterferenceFunctionLinear1DParaCrystal

### ISSUE THREAD

**Issue by mikapfl** [scgmlz/BornAgain#110]
Hi,

IsGISAXS has the "1DDL" interference function, which is a linear one-dimensional para-crystal (as far as I understand), i.e. similar to the InterferenceFunction1DLattice, but with a para-lattice. In BornAgain, there exist at the moment only the InterferenceFunction2DParaCrystal and the (pseudo one-dimensional) InterferenceFunctionRadialParaCrystal, but neither can be used to emulate a one-dimensional para-crystal.
I'd like to reproduce the findings in ["Grazing-incidence small-angle X-ray scattering of soft and hard nanofabricated gratings"](http://dx.doi.org/10.1107/S0021889812030415), which were obtained with the 1DDL interference function in IsGISAXS as far as I understand and it would be great to use BornAgain for that. (-:

Cheers

Mika

**Comment by waltervh** [comment]
Hi Mika,
Actually, when you look at the source code for IsGISAXS, you will see that the 1DDL interference function there is also a radial paracrystal, meaning that the modulus of the in-plane q component is used to calculate the interference. This is exactly as in BornAgain, so you should be able to reproduce the results you mentioned.

Kind regards,
Walter
