### ISSUE TITLE
Clarify whether 1D and 2D may be different type of projects

### ISSUE THREAD

**Issue by gpospelov** [scgmlz/BornAgain#1173]
Would it be sensible to start a project with defining "I want to create a project for 1D data/instruments/fitting" and then present only the 1D instruments, 1D data import and so on to the user within this project? Or are 1D and 2D relevant in the same project?

**Comment by mpuchner** [comment]
Only to make sure - this issue is not about programming, but about clarifying whether this could be a requirement

**Comment by gpospelov** [comment]
### User story

The user is developing the technology to grow gold nano-particles inside material bulk. He wants to know how the diameter of particles depends on the pressure in the chamber.

#### Part I

User grows in the chemical laboratory the sample, It is made of several thin layers and contains embedded gold particles. He goes to another laboratory in the basement and measures specular scattering from that sample using a table reflectometer. That gives him an ASCII file with 1D reflectance curve (intensity measured in the point-like detector as a function of incident angle).

He returns to the office, starts BornAgain, creates 1D instrument, types in parameters of the instrument as in the lab. He loads 1D curve from the file he has. Then, using MaterialEditor and LayerEditor he creates a sample, representing a multilayer. At this stage, the existence of gold particles is not important (the reflectometer doesn't see them). 

The task now is to try to understand the generic structure of the bulk of the sample.

The exact parameters of the multi-layer are not known. User makes an educated guess about materials (by providing approximate scattering length densities (SLD)), a number of layers, their thicknesses, and roughnesses.

The user puts simulated and experimental curves on one canvas and runs a quick simulation. Both curves show some wiggling with different periods and amplitude. User enables real-time simulation and starts to play with parameters: the value of roughness, SLD's, number of layers, etc.

As soon as they start to look alike, this part is over.

> This part is more or less implemented in `gui2`.

**Comment by gpospelov** [comment]
#### Part II

The user loads the same project and switches to the `Fitting` tab. His sample is already defined, data is loaded, and some reasonable sample parameters are already typed in.

Now the user wants to know the exact parameters of the sample. Particularly, he wants to find the thickness of the internal layer and its SLD. He marks corresponding parameters as `fit parameters` and runs fitting. Fitting will run simulation automatically in the background in a loop. In this loop, the algorithm will adjust the values of fit parameters. The algorithm will compare the simulated curve with the experimental curve on each iteration. Eventually, optimal values of fitting parameters will be reported.

> This part is not implemented in `gui2`. According to the roadmap, it should
> come in 2022. Partly it is implemented in `gui1`.

**Comment by gpospelov** [comment]
#### Part IV

Now the only one question left. Parameters of multi-layer obtained at stage II, and parameters of gold particle obtained at stage III, must be correlated. We can't fully trust their values, obtained in two independent fits.

We set up a new fitting job. It will use the same sample description as before, but two different instruments and two different data sets. The fit will have two fit parameters: the thickness of the middle layer, and the particle radius.

The algorithm will tune their values simultaneously, validating two simulation results (1D and 2D) against two experimental datasets (1D reflectivity curve and 2D map).

In the end, we will get verified values of fit parameters and estimation of correlation coefficients.

**Comment by gpospelov** [comment]
### Summary

> As you can see from the story, 1D-part and 2D-part  most of the time are two
> separate activities. They share the same sample description, the rest is
> different. But simultaneous fitting (the final stage), is possible only if 1D
> and 2D are the part of a single project. `gui1` now allows to handle 1D and 2D
> data in a single project, but doesn't allow simultaneous fitting. It is
> possible only via BornAgain Python interface.

**Answer**: 1D and 2D are relevant in the same project.

**Comment by gpospelov** [comment]
Seems to be resolved. Closing.
