### ISSUE TITLE
Download link for 1.18.0 on website broken

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#1187]
Trying to download the latest version from https://www.bornagainproject.org/download/ for windows clicking the links has no effect. 
Download from http://apps.jcns.fz-juelich.de/src/BornAgain works normally.

Using Google Chrome browser.

**Comment by helenibr** [comment]
I have the same problem!
Did u find a solution?

**Comment by jwuttke** [comment]
Thanks for reporting. We are investigating.

**Comment by jwuttke** [comment]
Sorry, colleagues, there has been a fatal failure of a cooling system, and in consequence we cannot access several of our servers. Worse, this happened as we were in the middle of major reconfiguration work. Right now, we are unable to update the BornAgain website to inform about this problem or to fix links.

BornAgain 1.18 for Windows with Python 3.9 can be downloaded from https://iffcloud.fz-juelich.de/s/7WzFLdyDW6tM7q9.

**Comment by jwuttke** [comment]
BornAgain 1.18 for Windows with Python 3.8 now also at https://iffcloud.fz-juelich.de/s/7WzFLdyDW6tM7q9.

**Comment by helenibr** [comment]
Thank you Joachim.
I just installed BornAgain 1.18 for Windows with Python 3.8 and it works !

Best regards
Helen Ibrahim


De : Joachim Wuttke<mailto:notifications@github.com>
Envoyé le :vendredi 5 février 2021 16:09
À : scgmlz/BornAgain<mailto:BornAgain@noreply.github.com>
Cc : helenibr<mailto:helenibrahim_@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [scgmlz/BornAgain] Download link for 1.18.0 on website broken (#1187)


BornAgain 1.18 for Windows with Python 3.8 now also at https://iffcloud.fz-juelich.de/s/7WzFLdyDW6tM7q9.

**Comment by jwuttke** [comment]
should be resolved by now
