### ISSUE TITLE
Wrongly defined python package file

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#1198]
In BA\python\bornagain\__init__.py the import of all sub-packages is relative without explicit declaration and a duct-tape solution of adding local file path to os.path is imposed and sub-packages are Imported as basic modules. 

This confuses IDE code inspection and is generally bad practice. I would propose the following changes:
1. delete line 8: 
`sys.path.append(os.path.abspath(os.path.dirname(__file__)))`
2. modify import statement, at least for python3, to:
```
from .libBornAgainBase import *
from .libBornAgainFit import *
from .libBornAgainParam import *
from .libBornAgainSample import *
from .libBornAgainDevice import *
from .libBornAgainCore import *
```

**Comment by jwuttke** [comment]
Implemented as you proposed, but breaks our tests: https://jugit.fz-juelich.de/mlz/bornagain/-/merge_requests/28.

**Comment by aglavic** [comment]
Looks to me as an error in your example files, all break at the same line:
`import ba_plot`

This should be replaced by:
`from bornagain import ba_plot`

**Comment by jwuttke** [comment]
Resolved https://jugit.fz-juelich.de/mlz/bornagain/-/merge_requests/105. Thanks for your analysis, Artur!
