### ISSUE TITLE
Spin-flip reflectivity from non-magnetic sample

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#1200]
When running reflectivity simulations on non-magnetic samples, spin-flip channels have the same intensity as non spin-flip from the nuclear structure.

### Expected behavior
spin-flip intensity should be zero if polarization efficiency is 100%

### Actual behavior
spin-flip = non spin-flip

**Comment by rbeerwerth** [comment]
Thanks for reporting this issue!
This happens when setScan is called after setting polarization and analyzer properties. As a workaround make sure to call setScan immediately after creating the SpecularSimiulation object.
