### ISSUE TITLE
Coupled Parameter Distribution

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#1216]
I'm trying to create a sample with a 1D lattice of Box-Particles that has domains that are randomly distributed. As the particle itself is not rotated together with the Xi-value of the lattice I want to calculate the in-plane rotation with Xi and particle rotation coupled.

How do I define a distribution of two parameters that can not be defined together as a wildecard?

I tried to link the second parameter to the distirbution as in the particle distribution example, but this does not seem to work for general model parameters:  
```
xi_min = -60.0*deg
xi_max = 60.0*deg
xi_distr = ba.DistributionGate(xi_min, xi_max)
dist=ba.ParameterDistribution("*/Interference1DLattice/Xi", xi_distr, 60)
dist.linkParameter("*/Particle/ZRotation/Angle")
simulation.addParameterDistribution(dist)
```

**Comment by jwuttke** [comment]
It is high on our agenda to rework the parameter distribution mechanism entirely.

Based on the extant mechanism we are unable to provide help. Sorry.
