### ISSUE TITLE
Build of 1.18 requires libcerf FZJ own library

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#1227]
I'm trying to compile version 1.18 on a cluster but the requirement of the FZJ own libcerf is not fullfilled.

Is there any way I can tell cmake for BornAgain about a custom libcerf installation/build path as with the Eigen3_DIR environment variable?

Generally it would be helpful if Compilation of BornAgain would not require so many external libraries, which often are not available on server systems, especially in the recent versions. It would be helpful to provide an installation script that downloads and compiles all these dependencies in a closed environment.

**Comment by aglavic** [comment]
Seems I found a solution myself:

Add  _-DCMAKE_FIND_ROOT_PATH=%install path for library%_ to the cmake call for BornAgain build.

**Comment by jwuttke** [comment]
Thank you for having documented the solution.

Regarding deployment to Linux: I presume we should invest effort not into making compilation easier, but rather into delivering a Debian binary package.
