### ISSUE TITLE
an error occur when compiling the software on HPC

### ISSUE THREAD

**Issue by Christian-lyc** [scgmlz/BornAgain#1229]
Hi, I just had a problem with installing BornAgain on HPC. 
The error is from compiling part, as following,

./../../lib/libgtest.so: error: undefined reference to 'std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()', version 'GLIBCXX_3.4.26'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/TestMinimizers] Error 1
make[1]: *** [Fit/Test/Minimizer/CMakeFiles/TestMinimizers.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

and

../../../lib/libgtest.so: error: undefined reference to 'std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()', version 'GLIBCXX_3.4.26'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/UnitTestFit] Error 1
make[1]: *** [Fit/Test/Unit/CMakeFiles/UnitTestFit.dir/all] Error 2

Do you know what should I do or what may cause this error? Thank you.

Best regards,

**Comment by mpuchner** [comment]
@Christian-lyc The BornAgain repository has been moved to https://jugit.fz-juelich.de/mlz/bornagain.
Could you please be so kind and create this issue in the related issue tracker: https://jugit.fz-juelich.de/mlz/bornagain/-/issues

**Comment by Christian-lyc** [comment]
Thank you for your reply
@mpuchner Here is the link
https://jugit.fz-juelich.de/mlz/bornagain/-/issues/82
Thank you
