### ISSUE TITLE
Confusing note in theory section of user manual

### ISSUE THREAD

**Issue by mikapfl** [scgmlz/BornAgain#142]
Hi,

in the BornAgain user manual at page 32 in subsection 3.1 Generic scattering cross section there is a warning box stating
> Currently, BornAgain uses the given vp (given through a particle refractive index) in
> place of the difference vp − vm(z). In other words, BornAgain does not subtract the
> matrix SLD from the particle SLD; it leaves it to the user to do this subtraction before
> entering the particle refractive index.
However, when I did some test calculations with a very simple layout consisting of three layers (substrate, layer, vacuum) with a box embedded in the layer everything behaved as if that note wasn't true:
* When using the same material for layer and box, there was no scattered intensity at all
* When using a different material for layer and box, there was scattering from the box
* When using vacuum as the material for the box and something else for the layer, there was scattering from the box.

So either I don't understand the note, or it is wrong. I understand the note such that when putting particles into a layer, instead of giving the refractive index of the particle material, I should input the difference in refractive index from the layer material. That would be pretty confusing, honestly and I suspect the note is just wrong and nowadays BornAgain does actually do the subtraction itself.

Cheers

Mika

**Comment by waltervh** [comment]
You are absolutely right. The note is wrong. I merged your pull request in the meantime, so I will close this issue. Thanks for pointing this out!
