### ISSUE TITLE
Error importing bornagain in Python 3

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#154]
Bornagain 1.7.1 can't be used with python 3 as expected, the import in python raises following exception:
>>> import bornagain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/BornAgain/lib/BornAgain-1.7/bornagain/__init__.py", line 7, in <module>
    from libBornAgainFit import *
  File "/opt/BornAgain/lib/BornAgain-1.7/libBornAgainFit.py", line 28, in <module>
    _libBornAgainFit = swig_import_helper()
  File "/opt/BornAgain/lib/BornAgain-1.7/libBornAgainFit.py", line 24, in swig_import_helper
    _mod = imp.load_module('_libBornAgainFit', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit__libBornAgainFit)

### Steps to reproduce the behavior
Compile BornAgain for python 3 as described in documentation, run source script and try to import in Python 3.

Calls used:

cmake -DBORNAGAIN_USE_PYTHON3=ON -DCMAKE_INSTALL_PREFIX=/opt/BornAgain ..
make -j6
sudo make install

source /opt/BornAgain/bin/thisbornagain.sh
python3
import bornagain

### Platforms affected
Ubuntu Linux 16.04 LTS
python 3.5.2
VirtualBox 64bit

**Comment by gpospelov** [comment]
Hi Arthur,

I was able to reproduce the problem. When configure BornAgain, CMake takes interpreter from Python3 and libraries from Python2. So even with the key -DBORNAGAIN_USE_PYTHON3 it is compiled for Python2. 

Seems to be a bug in CMake on given Ubuntu (plus lack of checks on our side).

I found a solution, which works for me:
apt-get install python3-dev

And then configure/compile from the scratch. Please let me know if it resolves your issue.

Regards
