### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by davidkleiven** [scgmlz/BornAgain#17]
Hi,

I experienced some installation problems.

1) The documentation did not compile and the error message
```
! Undefined control sequence.
<recently read> \symbf 
                       
l.524 ...ering angles, and $\symbf{q}$ components}
```
showed up. 

A quick fix that worked for me was to add 
```
\providecommand{\symbf[1]}{\mathbf{#1}}
```
to the preamble in *BornAgainManual.tex*.

2) Besides the packages listed in the README file I needed to install
* libyaml-cpp-dev
* libtiff-dev
* python-yaml
* qttools5-dev

3) The code did not compile. The error message was
```
/system/specific/path/BornAgain/GUI/coregui/Views/ImportDataWidgets/LinkInstrumentManager.h:70:17: error: field ‘m_instrumentNames’ has incomplete type ‘QStringList’
     QStringList m_instrumentNames;
```

a quick fix that worked for me was to add
```cpp
#include <QStringList>
```
to *LinkInstrumentManager.h*.

After this the code compiled and it passed all tests.

**Comment by gpospelov** [comment]
Hi, thanks for your input!

So far I have switched default branch from "develop" to "master" to make cloned repositories appearing on "master" branch by default. Master is stable and corresponds to our releases.
1) Thanks, we will fix it. But I wouldn't recommended to build manual by yourself. Please use pdf from bornagainproject.org 2) We will update installation instructions right before next release. 3) Right, thanks.

**Comment by davidkleiven** [comment]
Ok, I will close the issue.
