### ISSUE TITLE
compilation of 1.8.0 fails on openSUSE with obscure error about hashmaps

### ISSUE THREAD

**Issue by mikapfl** [scgmlz/BornAgain#188]
Hi,

I'm pretty excited about the graded layer approximation / cross-layer form factors and would like to try it out, but I am not successful in compiling 1.8.0 on openSUSE 42.2. Specifically, I get the following error from make:
```
[ 25%] Building CXX object Core/CMakeFiles/BornAgainCore.dir/Computation/MainComputation.cpp.o
In file included from /usr/include/c++/4.8/unordered_map:47:0,
                 from /home/mpfluege/software/bornagain/BornAgain/Core/Multilayer/MatrixFresnelMap.h:22,
                 from /home/mpfluege/software/bornagain/BornAgain/Core/Computation/MainComputation.cpp:20:
/usr/include/c++/4.8/bits/hashtable.h: In instantiation of ‘class std::_Hashtable<BasicVector3D<double>, std::pair<const BasicVector3D<double>, std::vector<MatrixRTCoefficients> >, std::allocator<std::pair<const BasicVector3D<double>, std::vector<MatrixRTCoefficients> > >, std::__detail::_Select1st, std::equal_to<BasicVector3D<double> >, HashKVector, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >’:
/usr/include/c++/4.8/bits/unordered_map.h:100:18:   required from ‘class std::unordered_map<BasicVector3D<double>, std::vector<MatrixRTCoefficients>, HashKVector>’
/home/mpfluege/software/bornagain/BornAgain/Core/Multilayer/MatrixFresnelMap.h:50:45:   required from here
/usr/include/c++/4.8/bits/hashtable.h:268:7: error: static assertion failed: Cache the hash code or make functors involved in hash code and bucket index computation default constructible
       static_assert(__if_hash_not_cached<
       ^
/usr/include/c++/4.8/bits/hashtable.h: In instantiation of ‘class std::_Hashtable<std::pair<double, double>, std::pair<const std::pair<double, double>, std::vector<ScalarRTCoefficients> >, std::allocator<std::pair<const std::pair<double, double>, std::vector<ScalarRTCoefficients> > >, std::__detail::_Select1st, std::equal_to<std::pair<double, double> >, Hash2Doubles, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >’:
/usr/include/c++/4.8/bits/unordered_map.h:100:18:   required from ‘class std::unordered_map<std::pair<double, double>, std::vector<ScalarRTCoefficients>, Hash2Doubles>’
/home/mpfluege/software/bornagain/BornAgain/Core/Multilayer/ScalarFresnelMap.h:50:46:   required from here
/usr/include/c++/4.8/bits/hashtable.h:268:7: error: static assertion failed: Cache the hash code or make functors involved in hash code and bucket index computation default constructible
Core/CMakeFiles/BornAgainCore.dir/build.make:1550: recipe for target 'Core/CMakeFiles/BornAgainCore.dir/Computation/MainComputation.cpp.o' failed
make[2]: *** [Core/CMakeFiles/BornAgainCore.dir/Computation/MainComputation.cpp.o] Error 1
CMakeFiles/Makefile2:1446: recipe for target 'Core/CMakeFiles/BornAgainCore.dir/all' failed
make[1]: *** [Core/CMakeFiles/BornAgainCore.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

```

Attached is the full `script` transcript of the cmake+make call, which hopefully contains all vrsion information. The only thing I can think of is that gcc 4.8 might not cut it anymore for 1.8.0?

Cheers

Mika
[bornagain18_build.txt](https://github.com/scgmlz/BornAgain/files/913219/bornagain18_build.txt)

**Comment by gpospelov** [comment]
Hi Mika,

you are right, 4.8 doesn't fully support C++-11, we need gcc 4.9 at least. On OpenSuse 42.2 you can install gcc5 via package manager.

Then, either you compile BornAgain with additional CMake keys to point it to the right compiler, or you use `update-alternatives` packages to make gcc5 default on your system.


### Method A) Additional keys in CMake

```
cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 <source>
```

### Method B) Configure with update-alternatives

I took the recipe from [here](http://askubuntu.com/questions/26498/choose-gcc-and-g-version), it works also for OpenSuse 42.2

Step I) Make update-alternatives familiar with gcc (yes, all these commands, but you have to do it only once)

```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20

sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20

sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
sudo update-alternatives --set cc /usr/bin/gcc

sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
sudo update-alternatives --set c++ /usr/bin/g++
```

Step 2) Switch between compilers

```
sudo update-alternatives --config gcc
sudo update-alternatives --config g++
```
As soon as you have selected gcc5 compiler, it will be default on your system, then compile BornAgain normally.

Cheers

**Comment by gpospelov** [comment]
Just for your info,

in BornAgain you will find following new examples related to sliced particles and graded layers
* simulation/ex06_Miscellaneous/CylindersInAverageLayer.py
* simulation/ex06_Miscellaneous/HalfSpheresInAverageTopLayer.py
* simulation/ex04_ComplexShapes/ParticlesCrossingInterface.py
* simulation/ex04_ComplexShapes/BiMaterialCylinders.py

Following tests from our functional test machinery are intended for validation of sliced machinery
* Tests/Functional/PyCore/legacy/sliced_spheres.py
* Tests/Functional/PyCore/legacy/sliced_composition.py

Cheers

**Comment by mikapfl** [comment]
Hi Gennady,

thanks for your information. Maybe you could update the minimum required versions at http://bornagainproject.org/documentation/installation/unix/install_third_party_software then, it still says gcc >= 4.8.

I'll try to compile with gcc 5 today.

Cheers

Mika

**Comment by gpospelov** [comment]
Done, thanks.

**Comment by mikapfl** [comment]
Yes, with gcc 5 compilation and tests work, thanks a lot!
