### ISSUE TITLE
BornAgain build fails on system with newer boost library

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#203]
On Ubuntu 17.04 (amd64) with the default boost library version 1.62.0 the build fails, referring a missing boost component with version 1.61.0. The output of cmake and make are in the first attached file.

The library, however seems to work normally after "make install".

Installing packages for libboost-date-time1.61.0 libboost-filesystem1.61.0 libboost-iostreams1.61.0 libboost-regex1.61.0 libboost-system1.61.0 leads to a different, referring to an undefined symbol. Output of make in attachment 2.

[build_output.txt](https://github.com/scgmlz/BornAgain/files/1054726/build_output.txt)
[build_output_2.txt](https://github.com/scgmlz/BornAgain/files/1054728/build_output_2.txt)

**Comment by gpospelov** [comment]
Hi,

concerning your first log, seems that there is a mixture of boost libraries 1.61 and 1.62 on your system, and CMake is not able to deduce consistent list of them for compiling/linking (I expect that headers for compilation are taken from one version  and libraries for linking from another). Is it possible to uninstall 1.61 completely (libraries and headers)? If not, then you might  try to specify exact path to 1.62 headers and libraries using -DBOOST_INCLUDEDIR= and -DBOOST_LIBRARYDIR=. See https://stackoverflow.com/questions/3016448/how-can-i-get-cmake-to-find-my-alternative-boost-installation for more details.

Your second log is something completely different. Looks like you are compiling new version of BornAgain while there is an old version of BornAgain in your PATH and LD_LIBRARY_PATH. And this old version got linked to unit test (linking error we see in your log). Try to unset PATH and LD_LIBRARY_PATH before compiling new BornAgain.

**Comment by aglavic** [comment]
Hi,

I don't have any boost library file of 1.61 installed on the system, but I think you are on to something with the previous BornAgain version. These have been compiled against version 1.61, which could cause this problem.
I ran the build again with reset PATH and LD_LIBRARY_PATH and now got a different error.

[debug.txt](https://github.com/scgmlz/BornAgain/files/1085306/debug.txt)

**Comment by gpospelov** [comment]
Hi,

good, seems that previous behaviour is because of conflicting with existing installation. We have to update installation instruction.

Last failure is because of GUI unit test, which checks how project autosave feature is functioning. 
If it is the only problem, one can ignore it, at least for Python usage. But anyway, I would like to find the reason.

Could you please check content of your build directory. To you have in it following subdirectories
<build-directory>/Tests/UnitTests/GUI/test_autoSave
and inside it, the file "document.pro" ?

Thanks!

In your build

**Comment by aglavic** [comment]
Yes, the directory exists and contains the following files:
autosave  document.pro  realdata.int.gz

**Comment by gpospelov** [comment]
Considering as solved
