### ISSUE TITLE
Thread count issue on Windows

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#322]
On Interl I7 Hexacore with 12 threads simulations don't run on all cores when set to Max (12 threads), this is observed in the amount of time the simulationes take and the CPU usage (total 12%). Only by reducing the thread number to 9 leads to expected performance.

### Expected behavior
Max threads should lead to 100% CPU utilization and fast simulations.

### Actual behavior
Total of 12% CPU utilization is measured and simulations are slow.

### Steps to reproduce the behavior
Run any simulation on Hexacore with hyperthreading and Windows GUI.

### Platforms affected
Windows 10 Home, 64bit, Born Again 1.10.0, Intel i7-5930K 6-core, 12 logical processors, 32 GB RAM

**Comment by gpospelov** [comment]
Thanks for the detailed info. We saw already something very similar on AMD Ryzen (16 threads available, only 8 can be used) and I though it is AMD specific. Will investigate.

**Comment by waltervh** [comment]
This issue should be solved in our current release (v1.11). Can you test and possibly close this issue?

**Comment by aglavic** [comment]
Solved with v1.11.
