### ISSUE TITLE
Cannot enter negative delta in Material Editor

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#325]
When trying to define materials with negative SLD from the GUI, the Editor prevents entering negative values for delta. This prevents to define negative SLD materials, which are physically possible in neutron scattering and resonant x-ray scattering.

### Expected behavior
Any floating point number can be entered as delta. Maybe changing the font to red color to indicate a non-standard value.

### Actual behavior
It is not allowed to enter a "-" sign.

### Steps to reproduce the behavior
Build model in GUI and open Material Editor to enter negative value as delta.

### Platforms affected
Windows 7, BornAgain 1.10.0

**Comment by waltervh** [comment]
Ok, created an issue in our current sprint to enable entering negative values
