### ISSUE TITLE
Unexpected contrast of buried particles

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#326]
Embedding void particles (0 SLD) into material layer leads to no scattering, i.e. the contrast is 0. This is in opposition to the example given in the documentation:
http://bornagainproject.org/node/70

### Expected behavior
The contrast for DWBA scattering should be the difference between particle and layer SLD.

### Actual behavior
The contrast is the particle SLD value.

### Steps to reproduce the behavior
Build any model with particles within a material layer. Minimalistic model attached.

### Platforms affected
Windows 7, BornAgain 1.10.0
[test.zip](https://github.com/scgmlz/BornAgain/files/1526328/test.zip)

**Comment by waltervh** [comment]
The attached file cannot be imported in BornAgain due to the absence of simulation files that were not included in the zip-file. Can you provide a version without any jobs run, please?

**Comment by aglavic** [comment]
Sorry, didn't know the jobs were needed, here without job runs.
[test.zip](https://github.com/scgmlz/BornAgain/files/1536413/test.zip)

**Comment by waltervh** [comment]
Np, we're working on exactly that (loading of projects without the job files)

**Comment by waltervh** [comment]
The project file you sent behaves as expected:
The particle with 'air' material sits in a layer of thickness zero, and because of its position coordinates, is located in the top 'air' layer. So no scattering because of zero contrast.

**Comment by waltervh** [comment]
To put the 'air' particle correctly inside the finite layer:
-Set the layer thickness to some finite value (bigger than the particle's height if you want it to be only in that layer)
-Set the particle's z-coordinate to at least minus its height, so it will be located in that layer (z-coordinate is relative to top interface, except for the top layer)

**Comment by waltervh** [comment]
Closing this issue since the simulation behaves as expected.
