### ISSUE TITLE
Examples on website still use getIntensityData()

### ISSUE THREAD

**Issue by mikapfl** [scgmlz/BornAgain#448]
Hi,

on the bornagainproject.org website in the Documentation (http://bornagainproject.org/documentation/python_examples), `getIntensityData()` is still used. I think that is spelled `result()` now.

Cheers

Mika

**Comment by gpospelov** [comment]
Hi,

we are now working on completely new web site. Hope to have it online soon. Examples and documentation will be updated there.

Cheers,
Gennady

**Comment by gpospelov** [comment]
Finally we have updated a website.
