### ISSUE TITLE
BornAgain 1.13.0 installer blocked by virus

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#663]
The windows x64 installer (py3 variant of 1.13.0) is detected by Traps as malicious activity and blocked for execution. This might be a result of the creation of the installer and was not the case in previous version.

**Comment by gpospelov** [comment]
Thank you for reporting this. We have checked installer/BornAgain on Windows 7 (Avast) and Windows 10 (Kaspersky) and it is working. Do you have, by chance, some extended error/log message from Traps? Which product of Traps product line you are using exactly? Thanks!

**Comment by aglavic** [comment]
It's the default virus tool at PSI in Version 4.2.1.
Here is the logfile entry from the tool for the installer call:
[virus.log](https://github.com/scgmlz/BornAgain/files/2480059/virus.log)

**Comment by gpospelov** [comment]
We have to get "trusted certificate" from Microsoft. It will make picky antiviruses happy. Closing the issue.
