### ISSUE TITLE
Compilation fails with munmap'ping an invalid pointer if other version of libgtest is in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by mikapfl** [scgmlz/BornAgain#677]
Hi,

I'm trying to compile bornagain 1.13.0 under opensuse leap 15.0 (with fftw3 installed from source) and I get an error from a test which looks a bit like a double free or so:
```
*** Error in `../../../bin/UnitTestCoreFitting': munmap_chunk(): invalid pointer: 0x0000000000f879f0 ***
make[2]: *** [Tests/UnitTests/Core/CMakeFiles/UnitTestCoreFitting_run.dir/build.make:57: Tests/UnitTests/Core/CMakeFiles/UnitTestCoreFitting_run] Abgebrochen (Speicherauszug erstellt)
make[1]: *** [CMakeFiles/Makefile2:2464: Tests/UnitTests/Core/CMakeFiles/UnitTestCoreFitting_run.dir/all] Fehler 2
make: *** [Makefile:163: all] Fehler 2
```

Actually, all the unit test that were compiled at that point are failing like this:
```
$ bin/UnitTestCoreNumeric0 
*** Error in `bin/UnitTestCoreNumeric0': munmap_chunk(): invalid pointer: 0x0000000000d8b380 ***
Abgebrochen (Speicherabzug geschrieben)
```

I couldn't attach a `script` transcript of the whole compilation which should contain all the versions etc., because github didn't want it, not even inside a zipfile. So I uploaded it to [the cloud(tm)](https://nc.helmholtz-berlin.de/index.php/s/AN9oy2JjFZMQJym). I don't quite know how to debug this further.

Cheers

Mika

**Comment by gpospelov** [comment]
Hi Mika,

thanks for reporting this.

Could you please compile your fftw with
./configure --enable-shared

it will give you both libraries on the system, static and dynamic.
Please try clean BornAgain build after and let me know the results.

Thanks and cheers
Gennady

**Comment by mikapfl** [comment]
Hi Gennady,

thanks for the swift reply!

Unfortunately, recompiling fftw3 with --enable-shared did not change anything:
```
*** Error in `../../../bin/UnitTestCoreFitting': munmap_chunk(): invalid pointer: 0x00000000025509f0 ***
make[2]: *** [Tests/UnitTests/Core/CMakeFiles/UnitTestCoreFitting_run.dir/build.make:57: Tests/UnitTests/Core/CMakeFiles/UnitTestCoreFitting_run] Abgebrochen (Speicherauszug erstellt)
make[1]: *** [CMakeFiles/Makefile2:2464: Tests/UnitTests/Core/CMakeFiles/UnitTestCoreFitting_run.dir/all] Fehler 2
make: *** [Makefile:163: all] Fehler 2
```

Full log of the bornagain compilation again at: https://nc.helmholtz-berlin.de/index.php/s/2dGxdffop5fpcFF

The fftw3 compilation log is at: https://nc.helmholtz-berlin.de/index.php/s/GHSg98jwn5Pe6iZ

Cheers

Mika

**Comment by gpospelov** [comment]
Could that be that there is another BornAgain installed in the system? In principle if old Bornagain  libraries are in the path, the loader might use wrong one during unit test executable run.

**Comment by mikapfl** [comment]
Hi Gennady,

I am already trained to look out for other versions of BornAgain in the PATH, but due to your hint I looked in detail at the output of `ldd UnitTestCoreFitting` and found that there was a locally-built version of libgtest. Deleting that, compilation succeeds. (-:

I don't know if you want to make a warning like you already implemented for an old BornAgain in PATH also for libgtest or if libgtest has proper symbol versioning so that cmake could handle this, or if you just want to close the issue as solved. Thanks anyway!

Cheers

Mika

**Comment by gpospelov** [comment]
Hi Mika,

thank you very much for your investigation. The best way to fix it on our side would be to add hard-coded runtime search path (aka rpath) into BornAgain's unit tests executables. We will do it in next release(s). I would leave you issue open as a reminder.

Thanks again and cheers,
Gennady

**Comment by mikapfl** [comment]
Hi,

true, I started thinking about RPATH at some point but then forgot about it again once the compile started working. (%

RPATH mangling would definitely be the most straightforward solution for users.

Cheers

Mika

**Comment by gpospelov** [comment]
Hi, we did some investigation how to protect our binaries from potentially conflicting libraries in LD_LIBRARY_PATH.

* Hacking RPATH is possible but leads to side effects (for example, there is a subtle effects connected with libraries runtime load order while running unit tests from Qt creator IDE).
* It seems that RPATH recipe is considered as outdated nowadays.
* One have to use RUNPATH instead, which doesn't help against LD_LIBRARY_PATH.
* It seems that state of the art is to keep LD_LIBRARY_PATH clean and use it only for some specific debugging task.
* So we consider the content of LD_LIBRARY_PATH to be the responsibility of the user.

In BornAgain we will modify the way we setup environment - thisbornagain.sh will be removed.

This issue I will close. Thanks again for your help and observations.

Regards,
Gennady
