### ISSUE TITLE
Crash on Project Save

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#76]
During the Tutorial BornAgain GUI crashed repeatedly when trying to save the project in a specific folder. This did not occur when saving somewhere else.

BornAgain 1.7.0 from git compiled on Ubuntu 64bit 16.10.

**Comment by gpospelov** [comment]
What was the directory name/path, access rights/specifiers? Any suspicious Unicode characters (e.g. \uFFFD)?

**Comment by aglavic** [comment]
/home/glavic_a/data/BornAgainSimus/Workshop/fitting

2016-11-22 15:50 GMT+01:00 Gennady Pospelov <notifications@github.com>:

**Comment by gpospelov** [comment]
Considering as solved.
