### ISSUE TITLE
Getting a TypeError in method 'Simulation2D_setDetectorParameters'

### ISSUE THREAD

**Issue by georgeyumnam** [scgmlz/BornAgain#769]
Hi all,

I am newbie trying to use BornAgain to run off-specular simulations by using the latest version of BornAgain. However, I am getting this error.

```
File "/home/georgeyumnam/code/BornAgain/build/lib/BornAgain-1.14/bornagain/libBornAgainCore.py", line 16510, in setDetectorParameters
    return _libBornAgainCore.Simulation2D_setDetectorParameters(self, n_phi, phi_min, phi_max, n_alpha, alpha_min, alpha_max)
TypeError: in method 'Simulation2D_setDetectorParameters', argument 5 of type 'size_t'
```

I have called the function as follows:
```
simulation=ba.OffSpecSimulation()
simulation.setDetectorParameters(11, -phi_f_offspec*deg, phi_f_offspec,
                                     296/BIN, alpha_f_min*deg, alpha_f_max*deg)
```
where, a simple python type() call of the input variables for setDetectorParameters() returns:
`<class 'float'> <class 'float'> <class 'float'> <class 'float'> <class 'float'>` respectively. I am not sure what I am doing wrong as a Stackexchange post on this TypeError suggest that there is a stdlib.h call missing in the C program during compile, which seems to be not the case here. How can I correct this error?

**Comment by DmitryYurov** [comment]
Dear George,
The code is complaining about `296/BIN`, the 5th argument if taking hidden `self` into account. Depending on the python version this expression produces either an integer (Python 2) or a float (Python 3). The method expects a positive integer as an input, thus throwing an error if a float is passed. Try using `296//BIN`. It denotes integer division in Python 3.

**Comment by georgeyumnam** [comment]
Thank you, Dmitry,
This solved the problem. I am closing this issue.
Cheers!!
