### ISSUE TITLE
Simulations attribute error in GISASSimulation in getBeamIntensity()

### ISSUE THREAD

**Issue by georgeyumnam** [scgmlz/BornAgain#770]
Hi all,

Once again, I am stuck at an attribute error. I am trying to call getBeamIntensity().getArray() from `GISASSimulation` in BornAgain latest version and extract an array, however, it returns a float, unlike `getIntensityData()` in version 1.7.0 of BornAgain. Therefore, I am getting the Attribute error:
`AttributeError: 'float' object has no attribute 'getArray'`
 I saw the updates changes and the problems this was causing in the earlier version (http://apps.jcns.fz-juelich.de/redmine/issues/1558). I am unable to trace the changelog which substituted this function attribute `getIntensityData()` which allowed array operations such as `getIntensityData().getArray()`. Or is there a better way to do this in the newer version? 

Also, the UserManual associated with the latest version of BornAgain is still written for version 1.7.2. Is this version of the UserManual still applicable to the latest version of the code? I see that the UserManual 1.7.2 (included in the latest version) still includes getIntensityData in GISASSimulation.

**Comment by DmitryYurov** [comment]
Dear George,

If you want to access simulation result, you can use `result()` method of `Simulation` object:

```
simulation = GISASSimulation(...)
...
simulation.runSimulation()
...
result = simulation.result()
```

`numpy`-array of scattering intensities is accessed through `array` method of `SimulationResult` object:

```
data = result.array()
```

You can find more thorough explanation on dedicated [web-page](https://www.bornagainproject.org/documentation/working-with-python/accessing-simulation-results/).

**Comment by georgeyumnam** [comment]
Dear Dmitry, 
Thank you for your reply. This was the correct solution to my issue. 
Closing this issue.
Thank you very much.!!
