### ISSUE TITLE
Unable to reproduce the results of basic_fitting_tutorial.py 

### ISSUE THREAD

**Issue by georgeyumnam** [scgmlz/BornAgain#850]
Hi developers, 

I am currently testing Bornagain-15 on a Windows 10 PC, I have python3.7 installed and I installed BornAgain using the executable. I was trying to reproduce the fitting example: basic_fitting_tutorial.py, however this is the result that I have got:

![Figure_1](https://user-images.githubusercontent.com/12828126/61663797-070f6780-ac97-11e9-94c9-3c83831ca486.png)

I was wondering if this error is reproduced on other machines, with other architectures. I reproduced a similar fit on the same tutorial on Ubuntu, python3.7 with BornAgain-14. 

Could this be due to an error in my installation?

Thank you.

**Comment by gpospelov** [comment]
Hi,

everything is OK in your case - it doesn't converge for me too. There is a mismatch between (code on web site) and (code in repository), and picture on web site. Sorry for the confusion, we will fix it.

Regards,
Gennady

**Comment by juanmcloaiza** [comment]
> Hi developers,
> 
> I am currently testing Bornagain-15 on a Windows 10 PC, I have python3.7 installed and I installed BornAgain using the executable. I was trying to reproduce the fitting example: basic_fitting_tutorial.py, however this is the result that I have got:
> 
> ![Figure_1](https://user-images.githubusercontent.com/12828126/61663797-070f6780-ac97-11e9-94c9-3c83831ca486.png)
> 
> I was wondering if this error is reproduced on other machines, with other architectures. I reproduced a similar fit on the same tutorial on Ubuntu, python3.7 with BornAgain-14.
> 
> Could this be due to an error in my installation?
> 
> Thank you.

Hi @georgeyumnam , 

The fix is on its way. If you want to fix your script immediately, change the function `run_fitting()` you see [on the website](https://www.bornagainproject.org/documentation/tutorial-examples/fitting/basic/basic-fit-tutorial/) by the one below. The only change is actually on one line: `params.add("prism_base_edge", 12.*nm, min=0.01)` --> `params.add("prism_base_edge", 6.*nm, min=0.01)`.

```python
def run_fitting():
    """
    Setup simulation and fit
    """

    real_data = load_real_data()

    fit_objective = ba.FitObjective()
    fit_objective.addSimulationAndData(get_simulation, real_data)

    # Print fit progress on every n-th iteration.
    fit_objective.initPrint(10)

    # Plot fit progress on every n-th iteration. Will slow down fit.
    fit_objective.initPlot(10)

    params = ba.Parameters()
    params.add("cylinder_height", 4.*nm, min=0.01)
    params.add("cylinder_radius", 6.*nm, min=0.01)
    params.add("prism_height", 4.*nm, min=0.01)
    params.add("prism_base_edge", 6.*nm, min=0.01)

    minimizer = ba.Minimizer()
    result = minimizer.minimize(fit_objective.evaluate, params)

    fit_objective.finalize(result)

    print("Fitting completed.")
    print("chi2:", result.minValue())
    for fitPar in result.parameters():
        print(fitPar.name(), fitPar.value, fitPar.error)

    # saving simulation image corresponding to the best fit parameters
    # np.savetxt("data.txt", fit_objective.simulationResult().array()),
```

You should then get the following image:

![BasicFittingTutorial](https://user-images.githubusercontent.com/14291849/61699193-b5b8b400-ad3a-11e9-8f58-5dc1723e30fe.png)

**Comment by georgeyumnam** [comment]
Thank you, I get the converged fitting now.
