### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by georgeyumnam** [scgmlz/BornAgain#854]
This is not an issue, but a feature request. Especially regarding neutron reflectometry.

In the GUI tool, Please include more formats of the plot. For instance, the plot that the GUI currently prints is alpha_i vs alpha_f. Please include plotting options such as: 
1. p_i vs p_f, 
2. p_i + p_f vs p_i - p_f
3. p_i - p_f vs Q_z
where p is the momentum.

Also, the examples in the documentation is more focussed on GISAS simulations, Please include some more examples of OffSpecular simulation/fitting, if possible. 

Thank you very much.

**Comment by gpospelov** [comment]
We will have it in mind, thank you.
