### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by georgeyumnam** [scgmlz/BornAgain#876]
Hi,

Is there a way to save a simulation written in python to a .pro format used in the GUI?
I saw that there is a .treetostring() function that can print the simulation in a string format. Is there a similar way in which we can extract the tree to XML (which is the required format for the .pro file format)? Thank you.

**Comment by gpospelov** [comment]
Hi,

there is no direct way to save Python simulation in pro file. But there is an experimental feature to import Python simulation in the GUI. To do this, just use menu in GUI File/Import and select python script, like CylindersAndPrism.py from Example directory. Import widget will find all functions which look like a function to construct the sample, and will rebuild GUI model from it.

This feature works pretty well under Linux. Under Windows it depends pretty much on the way the Python is configured on the system, and might fail. So the feature is experimental and there is no tutorial yet.

Regards,
Gennady

**Comment by georgeyumnam** [comment]
Thank you for your reply. Importing python script works in Ubuntu with BornAgain v1.15.
