### ISSUE TITLE
Does BornAgain support uncoupled size distributions?

### ISSUE THREAD

**Issue by StarostinV** [scgmlz/BornAgain#879]
Hi, I have an informational question about the available functionality.

I haven't found any way to apply uncoupled size distributions when simulating GISAXS experiment. For instance, I want to simulate cylinders with uncoupled size distributions parallel (or radius with, let's say, log-normal distribution) and perpendicular (height with Gaussian distribution) to the surface.

This functionality is available in IsGISAXS software so I would like to know whether it is available here or not. In BornAgain so far I found only the linkParameter function which is used to apply distribution to more than one parameter, but in that case parameters are not independent from each other. 

Thank you in advance,
Vladimir

**Comment by gpospelov** [comment]
Hi Vladimir,

currently there is no way to add uncoupled distributions to particle parameters. Linked parameter, indeed, is just to scale other parameters proportionally together with the main one.

Possible workaround is to generate particles with desired distribution/sizes of particle parameters and add it manually to ParticleLayout. This is actually how ParticleDistribution is doing internally.

This workaround is a little extra work for user working from Python. For GUI it's not an option, of course.

We have to see, how easy it is to implement it in one of next releases. I will update this issue, when we have more details.

Regards,
Gennady

**Comment by StarostinV** [comment]
Thank you for this explanation, it solved the problem!
