### ISSUE TITLE
Solvent penetration in spheres array at the solid-liquid interface

### ISSUE THREAD

**Issue by Nparacini** [scgmlz/BornAgain#888]
Hi,

I am using Born Again to run GiSANS simulations of an hexagonally packed monolayer of silica nanoparticles deposited on a silicon crystal at the solid liquid (D2O) interface.

I have two questions: 

1)	Since the particles are spherical and there are gaps between them, what are these gaps filled with by default when I create the model?
2)	Is there a way in the software to fill these gaps with the solvent (D2O) to simulate a realistic solid-liquid interface?

Thank you

Nico

**Comment by georgeyumnam** [comment]
I think you might be looking for the embedded particle assembly: https://www.bornagainproject.org/documentation/tutorial-examples/layered-structures/buried-particles/

If this is not what you want, try the particle core-shell assembly.

**Comment by Nparacini** [comment]
Thanks, the embedded particles is what I was looking for! Is there a way to have an embedded core-shell particles assembly? That would be exactly what I need.

Cheers

**Comment by georgeyumnam** [comment]
Yeah, simply put a core-shell particle in the embedded system. The particle core-shell can be added like a particle.

**Comment by Nparacini** [comment]
Ok great, I didn't realize it was just a matter of changing the Z position. 

Problem solved, thank you!

Cheers

**Comment by gpospelov** [comment]
Thank you all for the question and for the answer. Closing the issue.
