### ISSUE TITLE
GISAXS simulation of pyramid nanostructure with size distribution.

### ISSUE THREAD

**Issue by chhyun-PAL** [scgmlz/BornAgain#892]
I have some question about GISAXS simulation for pyramid nanostructure applying size distribution.
 As shown in attatched file (python script), I tried to simulation non-truncated pyramid nanostructure (base_edge = 70 nm, height = 49.5 nm, alpha = 54.74 deg).
 And, I want to simulate applying size distribution in fixed alpha angle (54.74 deg) condition.

in line 30, when I apply "sigma = 0.0000001*base_edge", the simulation is working well.
But, when I entered a value above 0.0000001, the simulation did not work.
 
 Also when I try using the height vaule, the limit value is 0.0001578 (sigma = 0.0001578*height).
So, I wonder why has it limit in sigma value.

 Additionally, I tried to compare the simulation between BornAgain and IsGISAXS program.
As you can see the ppt file, I performed the simulation for pyramid nanostructure in IsGISAXS program. (R = 35 nm (2R = 70 nm), R_distribution = gaussian, SigmaR/R = 0.1)
 Please point out if I did something wrong .Also, please check and reply about the differences between them.

[Rect._Detector_DWBA_70nm_Size_distribution_pyramid.docx](https://github.com/scgmlz/BornAgain/files/4157795/Rect._Detector_DWBA_70nm_Size_distribution_pyramid.docx)
[BornAgain & IsGISAXS.pptx](https://github.com/scgmlz/BornAgain/files/4157796/BornAgain.IsGISAXS.pptx)

**Comment by gpospelov** [comment]
Hi,

thank you for your questions, some little wish from my side
+ when you attach Python script, please rename it to *.txt and attach as it is. Please do not put it inside word document. It destroys formatting and makes it difficult to run after.
+ when something doesn't work, please specify exact error message.
+ please post separate questions as separate issues, to make it easier for us to answer.

**About Pyramid simulation**

When you are simulating the pyramid, you have to be sure, that the base, the height and the angle satisfy criteria `height <= base_edge*tan(alpha)`. Please see Pyramid form factor description in the manual for details. If you put wrong parameters, simulation will fail with the error message like

> terminate called after throwing an instance of 'Exceptions::RuntimeErrorException' what():  ParameterPool::set_value_error() -> Attempt to set value 68.6 for parameter '/Particle/Pyrami /BaseEdge' failed. Parameter limits: 'nonnegative'. Original exception message: FormFactorPyramid() -> Error in class initialization with parameters base_edge:68.6 height:49.5054 alpha[rad]:0.955393 Check for 'height <= base_edge*tan(alpha)' failed.

It actually says, that your square-based pyramid is not a pyramid anymore with such parameters.

When you are trying to apply size distribution to one of parameters, you have to make sure, that same criteria 'height <= base_edge*tan(alpha)' is fulfilled for all values of distributed parameters.

For example, if you want to have a Gaussian for base_edge with mean 70*nm and sigma=10*nm, you
will have actual values for base_edge in the range
[70.0-10.0xsigma_factor, 70.0+10.0xsigma_factor]. For sigma_factor=2.0 it gives you pretty wide range for values of base_edge and for some of them, the condition 'height <= base_edge*tan(alpha)' will not fulfilled. This is the reason why your simulation fails.

**Possible solution**

1) You can provide smaller sigma_factor, or smaller sigma, or change "height" so 'height <= base_edge*tan(alpha)' is always fulfilled.

2) You can setup particle size distribution manually. You generate 100 pyramids with base_edge, height and angle distributed as you want, and add all 100 particles to same ParticleLayout manually. This is what ParticleDistribution is doing internally anyway.

**About comparison with IsGISAXS**

I don't know details about size distribution parametrization in isGISAXS, but I vaguely remember that there was a mistake with the sign of coefficients K2 and K4 in IsGISAXS implementation of Pyramid form factor. They should be multiplied by -1. You can check it if you compare formulas in IsGISAXS manual with it's fortran implementation in `Island_Fourier_mod.f90`

In any case, to compare BornAgain with IsGISAXS I would start from simpler case and compare pictures without size distribution as a start.

**Comment by gpospelov** [comment]
... then I consider issue as resolved. Thank you.

**Comment by chhyun-PAL** [comment]
Thank you for your comments.

I'am trying to that process.
