### ISSUE TITLE
Fmmm struture mesoporous structure simulation 

### ISSUE THREAD

**Issue by sherry93126** [scgmlz/BornAgain#898]
### Expected behavior
I have a experimental GISAXS pattern. I used the "mesocrystal" way to conduct the simulation. 
### Actual behavior
The structure I'd like to simulate is orthorhombic Fmmm. My main problem is that I can't obtain the similar peak positions. Let alone the intensities, shapes or detailed things, I can't obtain the similar patterns. I tried to change all the parameters, but most of them only changed the peaks shapes and intensities. I believe the lattice structure and meso rotation influence the peak positions a lot, but it doesn't work in the supposed way.
### Steps to reproduce the behavior
I attched my code here
[Fmmm.txt](https://github.com/scgmlz/BornAgain/files/4267228/Fmmm.txt)
I attached my experimental data and simulated data here
[Fmmm simulation.pptx](https://github.com/scgmlz/BornAgain/files/4267242/Fmmm.simulation.pptx)

**Comment by mganeva** [comment]
Hi,
if you use script provided in the tutorial [mesocrystal_4plots.py](https://www.bornagainproject.org/documentation/working-with-python/3d-nanoparticle-arrangements/mesocrystal_4plots.py) and adjust it for your sample, you will see, that there is an instrument calibration problem.

![Figure_1](https://user-images.githubusercontent.com/7290767/75681213-6b65c100-5c93-11ea-8695-14976cf4380f.png)

As one can see in the figure above, the beam center is not in right position. Thus, I recommend you the following:

1. Check and fix the instrument parameters: beam center coordinates and incident angle. Simplest way to do it is to load your experimental data in GUI (the `Data` view) and plot them in `Degrees` (`Properties` -> `Axis Units`). If the instrument parameters are correct, `alpha_f` of the specular peak should be equal to the `incident angle` you have set and `phi_f` of the specular peak should be equal to the `Azimuthal angle`. 

2. Check (and fix, if needed) the material properties (in your case `delta` and `beta`). They depend on the wavelength of the x-ray photon.

3. Only **after you get specular and Yoneda peaks at right positions** you might need to adjust the lattice parameters or mesocrystal rotation angles.

As I can see from your experimental data, you have definitely more than one rotation of the mesocrystal. See the tutorial [3D nanoparticle arrangements](https://www.bornagainproject.org/documentation/working-with-python/3d-nanoparticle-arrangements/), chapter on rotational distribution. You will find there samples of the Python code to add a rotational distribution.

You can download Python script adjusted for your data using the link below:
[mesocrystal_4plots.zip](https://github.com/scgmlz/BornAgain/files/4275766/mesocrystal_4plots.zip)

**Comment by sherry93126** [comment]
> Hi,
> if you use script provided in the tutorial [mesocrystal_4plots.py](https://www.bornagainproject.org/documentation/working-with-python/3d-nanoparticle-arrangements/mesocrystal_4plots.py) and adjust it for your sample, you will see, that there is an instrument calibration problem.
> 
> ![Figure_1](https://user-images.githubusercontent.com/7290767/75681213-6b65c100-5c93-11ea-8695-14976cf4380f.png)
> 
> As one can see in the figure above, the beam center is not in right position. Thus, I recommend you the following:
> 
> 1. Check and fix the instrument parameters: beam center coordinates and incident angle. Simplest way to do it is to load your experimental data in GUI (the `Data` view) and plot them in `Degrees` (`Properties` -> `Axis Units`). If the instrument parameters are correct, `alpha_f` of the specular peak should be equal to the `incident angle` you have set and `phi_f` of the specular peak should be equal to the `Azimuthal angle`.
> 2. Check (and fix, if needed) the material properties (in your case `delta` and `beta`). They depend on the wavelength of the x-ray photon.
> 3. Only **after you get specular and Yoneda peaks at right positions** you might need to adjust the lattice parameters or mesocrystal rotation angles.
> 
> As I can see from your experimental data, you have definitely more than one rotation of the mesocrystal. See the tutorial [3D nanoparticle arrangements](https://www.bornagainproject.org/documentation/working-with-python/3d-nanoparticle-arrangements/), chapter on rotational distribution. You will find there samples of the Python code to add a rotational distribution.
> 
> You can download Python script adjusted for your data using the link below:
> [mesocrystal_4plots.zip](https://github.com/scgmlz/BornAgain/files/4275766/mesocrystal_4plots.zip) You will need `fabio` Python module to load your experimental data.

Hi,
Thanks for your help. You showed me an important problem.
 I'm trying to fix the instrument parameters but I meet a new problem. My incident angle is 0.3 degree. When I check the experimental data in GUI, it set the incident beam as (-0.3,0) in degree axis units. While when I check it in python, I gave it the exact same instrument parameters, it set the incident beam as (0,0) in degree axis units. I'm not sure which one I should use to do simulation fitting.

Best wishes,
Li

**Comment by sherry93126** [comment]
@mganeva 
Hi,

Thanks for the answer. Can I add more than one rotation distribution if I use mesocrystal way to do the simulation? 

Best wishes,
Sherry

**Comment by mganeva** [comment]
@sherry93126 Of course. You can use similar ways as suggested in the tutorial for particle compositions in lattice. For example, first you define the `rotations` dictionary:

```python
# rotations dictionary, consists of pairs "angle of rotation: weight"
# you can have as many pairs as you wish
rotations = {0.0: 0.7, 45.0: 0.3}
```

and then in your `get_sample` function you should create a loop to add rotated mesocrystals to the particle layout:

```python
layout = ba.ParticleLayout()
for angle in rotations.keys():
   meso_ff = ba.FormFactorLorentz(meso_width, meso_height)                 
   meso = ba.MesoCrystal(crystal, meso_ff)
   meso_rotation = ba.RotationZ(angle*deg)
   meso.setRotation(meso_rotation)
   layout.addParticle(meso, rotations[angle])
```

This example makes sense if you have **just a few rotations** and **do not consider interference** between mesocrystals. 

If you want to consider interference, then you should add a separate layout for each rotation (same way like in the tutorial referenced above). If you want to add a lot of rotations, you should consider distributions available in BornAgain and apply one of them to the mesocrystal rotation angle.

**Comment by sherry93126** [comment]
@mganeva 

Hi,

Thanks for your help. I added the example code you showed to me. But when I tried to change the parameters, nothing changed. I wonder if it's because "rotation" actually change the rotations of particles. As I used the symmetrical sphere as the particle, so nothing change if I rotate the sphere. I should add different rotations of the mesocrystal instead of the particle itself. Or is it because I type the wrong code? I attached my current code here, could you have a look?

Best wishes,
Sherry

[Fmmm fitting.txt](https://github.com/scgmlz/BornAgain/files/4308493/Fmmm.fitting.txt)
![Fmmm fiting](https://user-images.githubusercontent.com/61588601/76248876-3520d680-627d-11ea-89ed-b4c074b7114f.jpg)

**Comment by mganeva** [comment]
Hi Sherry,
you should replace the line

```python
meso_rotation = ba.RotationZ(42*deg)
```

with the line
```python
meso_rotation = ba.RotationZ(angle*deg)
```

otherwise you add only a single rotation by 42 degrees.

**Comment by sherry93126** [comment]
@mganeva

Hi,

Do you know how I can optimize the middle part of the pattern? It seems that the experimental data has stronger signal from the middle part. I guess the signal comes from the big particles of the surface but I'm not sure. Do you have any idea that where they come from and how I optimize it?

I heard the Europe is suffering the virus. Hope you stay safe and heath.
Wish you all the best.

Sherry

**Comment by mganeva** [comment]
Hi Sherry,

optimization of the central rod is not easy and not always possible. You may try to add some large particles to your model if they are observed by the imaging techniques. However, this might not solve the problem. The main issue is that in the central rod two kinds of scattering are present:

- specular reflection
- scattering from your sample

BornAgain in it's present implementation simulates only one of them (depending on your simulation settings). See also [this discussion](https://github.com/scgmlz/BornAgain/issues/893#issuecomment-588967302) for details. Usually intensity of specular scattering is much higher than scattering from the sample. However, for some ordered structures these intensities can be comparable.

If you are interested in vertical correlations of your sample, I recommend you to optimize not a central rod, but a slice along left or right first order peak. Here you can vary:

- Debye-Waller factor and/or
- Interface roughness

to influence the Intensity along `Qz`.

**Comment by jwuttke** [comment]
Closing for now.
