### ISSUE TITLE
Mapping of Fresnel coefficients/reflectivities on 2D detector 

### ISSUE THREAD

**Issue by ChristopherGreve** [scgmlz/BornAgain#900]
Hi, I am currently working on a coherent scattering problem in grazing incidence which is highly sensible on the different DWBA contributions, especially on the projection of the two true qz values on a nominal qz value on the detector.

Is it with BornAgain somehow possible to reveal the calculated fresnel coefficients mapped to a 2D detector? E.g. doing a qz cut for a given qr and analyse how the reflectivities for the DWBA terms vary with qz afterwards? 

It would be interesting to see how the reflectivities change the dominance for the first DWBA term in variation with incidence and exit angle and to identify for which experimental setup or q-region a description within the BA could be applied for (e.g. incidence and exit angle >> critical angle). 

Thank you!
Chris

**Comment by rbeerwerth** [comment]
Hi Chris,
I am a bit unsure about what you want to achieve and what your scenario actually looks like.
I assume, that you are talking about a GISAS computation, therefore, I prepared an example code to demonstrate in which direction you would have to head based on this example [example](https://www.bornagainproject.org/documentation/tutorial-examples/interference-functions/interference-2d-square-lattice/)

If, instead, you are working on a reflectivity calculation, maybe this [example](https://www.bornagainproject.org/documentation/working-with-python/basic-simulation-tutorial/depth-probe/) is enough to help you

The access to the Fresnel coefficients is possible, however, not from the Python interface. For this you would have to write a C++ program which essentially performs part of the internal routines from BornAgain. In the attached program, I demonstrate how to access the Fresnel coefficients from a GISAS computation (lines 110 and 111, or 116 or 117 for the whole multilayer). A variation of the angles could be "hacked" into this, e.g. in line 148. This can be extended to also extract and perform the intensity calculations for varying angles

Please also note, that the internals used in my code are in the process of changing, the next release will likely require an update of that code.

I hope this helps a bit further, if not please give us some more details of your scenario and what you want to achieve. It is unclear to me about which DWBA terms you are talking and how the reflectivity relates to that. As BornAgain by concept calculates the reflectivity as a function of the incident angle, you could then just run a specular computation.

Best

[example.tar.gz](https://github.com/scgmlz/BornAgain/files/4349995/example.tar.gz)

**Comment by ChristopherGreve** [comment]
Hi,

First your provided example helps a lot to work with the BornAgain internals. I will test it and if it works as expected this issue can be closed.

As you assumed I was talking about a GISAS computation (GISAXS). The mentioned DWBA terms are the 4 terms in the form factor, depending on the fresnel reflectivities of in- and outgoing angles (cases of reflection before, after or before and after scattering). 

For my given problem I want to use the calculated fresnel reflectivities/fresnel coefficients to deduce if terms of the form factor become dominant or can be neglected for my set of given incident angles (and corresponding outgoing angles on the detector).

**Comment by jwuttke** [comment]
In the foreseeable future we have no capacity to work on this. Therefore I'll close.
