### ISSUE TITLE
"ApplicationFailedException" error when running Python script via Visual Studio Code through Anaconda Navigator (Windows)

### ISSUE THREAD

**Issue by Apostolo5** [scgmlz/BornAgain#901]
Dear BornAgain Team,

![Problem_ApplicationFailedException](https://user-images.githubusercontent.com/61276654/75994852-dadde980-5efb-11ea-9dbe-a9ae08b34f2a.png)
Hello. I experienced today the following issue, on my PC (I use Windows 10 as operating system).  When I launch Visual Studio Code (with "Powershell" as the shell) via the Anaconda Navigator and try to run a python script that had been previously extracted from BornAgain GUI, I get this "ApplicationFailedException" error (highlighted with black color in the attached image). In fact, I was able to run the python script properly using this approach without any problem (even without lanuching Visual Studio Code via the Anaconda Navigator, the script used to run properly). The only difference that I recall is that I closed the python script and re-launched it at some moment. So, it is surprising why this error message only now appeared. Any feedback would be very helpful! Thank you very much, Apostolos Vagias

**Comment by juanmcloaiza** [comment]
Dear Apostolos, 


The problem you describe is not related to BornAgain, you may want to contact your sysadmin instead. Yet, I hope this little advice may help:

> In fact, I was able to run the python script properly using this approach without any problem

Use the approach you used on the past to make your script work. If the problem persists, take a look at https://github.com/scgmlz/BornAgain/issues/894; if the problem still persist:

1. Uninstall BornAgain.
2. Uninstall VScode.
3. Uninstall anaconda.
4. Follow the instructions in the BornAgain webpage: https://www.bornagainproject.org/documentation/getting-started/installation/windows/python-anaconda/


Cheers and good luck,
Juan
