### ISSUE TITLE
GISAXS fitting using real data of 2D images.

### ISSUE THREAD

**Issue by chhyun-PAL** [scgmlz/BornAgain#902]
### Expected behavior
 I would like to fit the real GISAXS data like as Basic fit example(https://www.bornagainproject.org/documentation/tutorial-examples/fitting/basic/basic-fit-tutorial/).
 But, I want to use the real GISAXS data of 2D images(.tif file) obtained by rectangular detector instead of text file(ex. "basic_fitting_tutorial_data.txt.gz").

### Actual behavior
It seems to be needed a text file rather than a 2D image for fitting process.

### Steps to reproduce the behavior
 I have some questions about that.
1. Could I do GISAXS fitting using 2D image file instead of text file?
2. If not, is there a way to convert a 2D image to a text file to fit?

**Comment by juanmcloaiza** [comment]
Dear @chhyun-PAL ,


In BornAgain 1.16.0 the behavior you describe is not reproduced.

![LoadTifImage](https://user-images.githubusercontent.com/14291849/76195017-b0d04400-61e7-11ea-89d3-69801d091415.png)

We would need more details about the error you're getting and the files you are trying to import (is there any error message?). The following link may be useful if you still want to convert your tiff files to ascii: https://stackoverflow.com/questions/33881554/how-do-i-lock-window-resizing-in-a-python-matplotlib-window


Cheers,
Juan

**Comment by mganeva** [comment]
`addSimulationAndData` method needs a numpy array with your experimental data. The example you mention creates it from the text file. For the .tif format you may use the approach from [real measurement example](https://www.bornagainproject.org/documentation/tutorial-examples/fitting/extended/experiment-at-galaxi/):

```python
def load_real_data(filename="data.tif"):
    """
    Loads experimental data and returns numpy array.
    """
    return ba.IntensityDataIOFactory.readIntensityData(filename).array()
```

Alternatively, you can also use external Python module [`fabio`](https://pypi.org/project/fabio/). It supports a lot of different file formats produced by the X-ray sources worldwide:

```python
import fabio
def load_real_data(filename="data.tif"):
    """
    Loads experimental data and returns numpy array.
    """
    img = fabio.open(filename)
    data = np.array(img.data, dtype='float')
    return data
```

**Comment by chhyun-PAL** [comment]
Thank you for your comments, I'll try it.

**Comment by chhyun-PAL** [comment]
1. I tried the fitting process with text file attached.
[Pyramid_data_2.txt](https://github.com/scgmlz/BornAgain/files/4322541/Pyramid_data_2.txt)
 I wonder that it is possible to use for fitting. 

2. I run the fitting with above text file about pyramid structure. But I didn't get the fitting results and error messages.
 (I attached the python script I used)
[TEST_pyramid_basic_fitting_tutorial.zip](https://github.com/scgmlz/BornAgain/files/4322561/TEST_pyramid_basic_fitting_tutorial.zip)
 Please confirm why is it not working.

**Comment by mganeva** [comment]
You have following problems in your script:

1.  Size of the detector and dimensions of the data file **must be the same**. However, in your script you set the dimensions to be

```python
 MX225_npx, MX225_npy = 1440, 1440  # number of pixels
```
although the file `Pyramid_data_2.txt` has dimensions (2880, 2880). You can easily check the dimensions of the data file with the following Python code:
```python
import numpy as np

data = np.loadtxt("Pyramid_data_2.txt")
print(data.shape)
```
Thus, you should set the number of detector pixels to be the same as dimensions of your data file:

```python
 MX225_npx, MX225_npy = 2880, 2880  # number of pixels
```

2. You should properly set the detector in sample in your GISAS simulation. Take a look how it is done in [tutorial fitting examples](https://www.bornagainproject.org/documentation/tutorial-examples/fitting/) provided on the BornAgain web page. Example [fitting of the real experimental data](https://www.bornagainproject.org/documentation/tutorial-examples/fitting/extended/experiment-at-galaxi/) might be helpful as well. Thus, your `get_simulation` function must contain **at least** the following lines:

```python
def get_simulation(params):
    """
    Return a GISAXS simulation with defined beam
    """
    simulation = ba.GISASSimulation()
    simulation.setBeamParameters(1.072157*angstrom, 0.115*deg, 0.0*deg)
    simulation.setDetector(get_rectangular_detector())
    simulation.setSample(get_sample(params))
    return simulation
```

3. Your detector is huge and fitting of the 2880x2880 GISAXS data will take ages even for a simple sample. To decrease the fitting time, I recommend you to set the region of interest. To do that, add to your `get_simulation` function the following line:

```python
simulation.setRegionOfInterest(xmin, ymin, xmax, ymax)
``` 

where `xmin`, `ymin`, `xmax`, `ymax` are coordinates of the rectangular region of interest in **mm** (for rectangular detector). You should replace them by appropriate numbers.

**Comment by chhyun-PAL** [comment]
I appreciate your comments! I'll try again based on this.
