### ISSUE TITLE
Monte-Carlo based integration of instrument resolution

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#913]
All GISANS experiments can have significant contributions from horizontal, vertical and wavelength distributions. When implementing these in BornAgain one quickly runs into huge simulation times, as each of the underlying distributions should at least have 5 points and thus the calculation time becomes 125x larger.

It would be useful if there was an option allowing random sampling from a group of distributions. (Optimally different values for each pixel.) I assume that already 20 such samples would give reasonable results. To be useful for fitting, however, the choice of parameters would need to be the same for all iterations and thus the random seed for this choice would need to be settable.

**Comment by juanmcloaiza** [comment]
Hi Artur,


what a coincidence, some days ago (precisely, Friday 13th), I was timing some simulations, but only with respect to the Montecarlo Points and the Instrument Resolution...

![image](https://user-images.githubusercontent.com/14291849/78222008-ba865800-74c4-11ea-95ec-8fa622fccc44.png)

My goal was only to have a rough estimate of the times Bornagain needed to run the "production" simulations, so I quickly interpolated the times depending on the number of Monte Carlo points and the resolution of the detector, but I'm glad that with this issue you provide us with a more complete picture:

<img src="https://render.githubusercontent.com/render/math?math=t=f  \times N_{MC} \times N_{xbin} \times N_{ybin} \times N_{P(x)} \times N_{P(y)} \times N_{P(\lambda)} ">

Is that correct? $f$ is just a constant factor depending on the hardware, which is another question I was pondering about... the feasibility of deploying jobs into an HPC cluster. I haven't had the time yet, so I'm glad you also came with an answer in [issue 914](https://github.com/scgmlz/BornAgain/issues/914), even if it does not look good!

> It would be useful if there was an option allowing random sampling from a group of distributions. (Optimally different values for each pixel.) I assume that already 20 such samples would give reasonable results. To be useful for fitting, however, the choice of parameters would need to be the same for all iterations and thus the random seed for this choice would need to be settable.

This sounds like a viable approach and clever suggestion, thank you. If I understand correctly, this would reduce the computation times to:

<img src="https://render.githubusercontent.com/render/math?math=t=f  \times N_{MC} \times N_{xbin} \times N_{ybin} \times N_{P(x, y, \lambda)} ">

right? (I'm not explicitly writing what each quantity represents, not to make this message even lengthier, I hope is self-explaining.)

Cheers,
Juan

**Comment by gpospelov** [comment]
To make the discussion in this thread more productive, one has to agree on the "instrument resolution" term. 

> I was timing some simulations, but only with respect to the Montecarlo Points and the Instrument Resolution...

Here it is about simple number of detector channels...

**Comment by aglavic** [comment]
Hi Juan,

I think all of your nomenclature is clear without further explanation.

I'm not sure how BornAgain handles the integrations of parameter distribution in general. But I would assume if the interaction with python only happens at the initialization of the model and when returning the data that this constant overhead is negligible. 
Therefore both of your formulas are what I would expect, too.

Gennady is correct, that the MC you are doing is on the detector pixel side, so the two issues are linear independent. 

Some of the beam resolution issues can be overcome by later FFT convolution (like phi resolution), but that does not work for all samples.

**Comment by jwuttke** [comment]
This is work in progress, as part of our current rewriting of the parameter distribution machinery.

Issue transfered to https://jugit.fz-juelich.de/mlz/bornagain/-/issues/28.
