### ISSUE TITLE
Question regarding model implementations

### ISSUE THREAD

**Issue by NisGellert** [scgmlz/BornAgain#933]
Hi

The X-ray group at DTU Space currently uses the IMD software, which is written in IDL, to analyse our reflectometry data. I am trying to find a substitute software that is Python based, and I came across BornAgain. 

Is it possible to fit the layer density in the current BornAgain software? 
Is it possible to define a rough/diffuse interface?
Is it possible to import own Optical constant files from NIST and LLNL?

Best regards
Nis C. Gellert

**Comment by rbeerwerth** [comment]
Hi,

In principle, all quantities can be fitted. For this purpose you need to create a set of parameters, make them known to the minimizer, and write a function that creates a sample with these parameters. This concept is seen in this [example](https://www.bornagainproject.org/documentation/cookbook/fitting/basic/minimal-fit-example/), where the `params` object holds only a single parameter, the radius. 
In [this](https://www.bornagainproject.org/documentation/cookbook/fitting/extended/real-life-reflectometry/), more complex, example, a concentration is fitted by varying the refractive index. This is probably pretty close to your use case.

Rough interfaces are indeed supported, see e.g. this [example](https://www.bornagainproject.org/documentation/cookbook/reflectometry/specular-simulation-with-roughness/). Please note that the example below currently works only in the development version, but will fully run in the next release. This will then support the selection of a roughness model based on either the analytical tanh or a Gaussian profile.

For reading optical constant files from other sources, it will be necessary to write some own functions in Python.

Best wishes

Randolf

**Comment by jwuttke** [comment]
Closing now. @NisGellert, please reopen the issue if you are not yet satisfied with the answer.
