### ISSUE TITLE
UnitTestNumeric fails on mac os x 10.15 

### ISSUE THREAD

**Issue by mganeva** [scgmlz/BornAgain#959]
UnitTestNumeric fails on mac os x 10.15 (Python 3.8.3)

The error message in the console:
```
The following tests FAILED:
	  3 - UnitTestNumeric (ILLEGAL)
```
The `LastTest.log` can be downloaded [here](https://github.com/mganeva/test/suites/728075754/artifacts/7274122)

**Comment by rbeerwerth** [comment]
Solved in PR 955, by reverting the test loop to the original gtest implementation. 
In addition the required accuracy for the cone6_steep test was relaxed in accordance with other tests.
