### ISSUE TITLE
Problem building BornAgain using GitHub actions

### ISSUE THREAD

**Issue by andyfaff** [scgmlz/BornAgain#963]
There is a [Github actions entry](https://github.com/reflectivity/analysis/blob/master/.github/workflows/validation.yml) for building and validating BornAgain as part of ORSO.
This has just started failing in the last day or so. The build log should [tell](https://github.com/reflectivity/analysis/pull/24/checks?check_run_id=746403372#step:7:985) what the matter is.

**Comment by gpospelov** [comment]
Thank you for reporting. Should be fixed now in #964

**Comment by andyfaff** [comment]
The original issue was fixed, but recent commits have broken the build again, https://github.com/reflectivity/analysis/runs/752033115.
```
[  1%] Built target gtest
[  1%] Building CXX object ThirdParty/Fit/RootMinimizers/CMakeFiles/RootMinimizers.dir/Minuit2/FumiliGradientCalculator.cxx.o
/home/runner/BornAgain/ThirdParty/GUI/qt-manhattan-style/stylehelper.cpp: In static member function ‘static void Manhattan::Utils::StyleHelper::drawIconWithShadow(const QIcon&, const QRect&, QPainter*, QIcon::Mode, int, const QColor&, const QPoint&)’:
/home/runner/BornAgain/ThirdParty/GUI/qt-manhattan-style/stylehelper.cpp:471:38: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
ThirdParty/GUI/qt-manhattan-style/CMakeFiles/ManhattanStyle.dir/build.make:96: recipe for target 'ThirdParty/GUI/qt-manhattan-style/CMakeFiles/ManhattanStyle.dir/stylehelper.cpp.o' failed
CMakeFiles/Makefile2:2259: recipe for target 'ThirdParty/GUI/qt-manhattan-style/CMakeFiles/ManhattanStyle.dir/all' failed
         int space = p->fontMetrics().horizontalAdvance('M') * 0.05;
                                      ^~~~~~~~~~~~~~~~~
make[2]: *** [ThirdParty/GUI/qt-manhattan-style/CMakeFiles/ManhattanStyle.dir/stylehelper.cpp.o] Error 1
make[1]: *** [ThirdParty/GUI/qt-manhattan-style/CMakeFiles/ManhattanStyle.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by gpospelov** [comment]
My fault, fixed in #966. I have to do something about that, either to provide build config for old Qt's, or rise minimum supported version to Qt 5.12 LTS.

**Comment by andyfaff** [comment]
The job that's failing uses Ubuntu:focal, I think. So the Qt version installed by apt is the most up to date packaged version.

**Comment by rbeerwerth** [comment]
According to https://github.com/actions/virtual-environments, ubuntu-latest currently refers to 18.04, which packages Qt 5.9.5. This seems to be consistent with the cmake output.

**Comment by andyfaff** [comment]
You're right. But installing various Pythons on `ubuntu-20.04` is proving problematic.

**Comment by andyfaff** [comment]
I think that `libqt5opengl5-dev` also needs to be installed on `ubuntu-20.04` for the build to work.

**Comment by gpospelov** [comment]
You are right. Recently I was struggling with custom docker focal-based container, the whole string was 
```
 build-essential git cmake libgsl-dev libfftw3-dev python3 python3-dev python3-numpy python3-matplotlib libtiff5-dev libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-iostreams-dev qt5-default libqt5designercomponents5 qttools5-dev libqt5svg5-dev libqt5opengl5-dev
```

**Comment by andyfaff** [comment]
> Actually our current Linux build is based on own focal-based container

Does that container, scgmlz/bornagain-dev:focal, have its own Dockerfile, I couldn't find it? This would aid in the validation attempt.

**Comment by gpospelov** [comment]
It is published on [DockerHub](https://hub.docker.com/orgs/scgmlz/repositories). In theory, this Dockerfile should be everything that you need to access the container. But I have no experience in using if from Actions system. If you need, I can send you the recipe how this container was prepared.

**Comment by andyfaff** [comment]
I eventually figured it out. It would be nice if the build requirements specified minimum values for things like Qt, and how to achieve them (e.g. you need Ubuntu > X.X).
